// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FriendsAppRequestsMsg.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace VrLifeShared.Core.Applications.DefaultApps.FriendsApp.NetworkingModels {

  /// <summary>Holder for reflection information generated from FriendsAppRequestsMsg.proto</summary>
  public static partial class FriendsAppRequestsMsgReflection {

    #region Descriptor
    /// <summary>File descriptor for FriendsAppRequestsMsg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FriendsAppRequestsMsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtGcmllbmRzQXBwUmVxdWVzdHNNc2cucHJvdG8SRlZyTGlmZVNoYXJlZC5D",
            "b3JlLkFwcGxpY2F0aW9ucy5EZWZhdWx0QXBwcy5GcmllbmRzQXBwLk5ldHdv",
            "cmtpbmdNb2RlbHMaF0ZyaWVuZHNBcHBVc2VyTXNnLnByb3RvIp4BChVGcmll",
            "bmRzQXBwUmVxdWVzdHNNc2cSDgoGdG9Vc2VyGAEgASgEEnUKEmZyaWVuZFJl",
            "cXVlc3RzTGlzdBgCIAMoCzJZLlZyTGlmZVNoYXJlZC5Db3JlLkFwcGxpY2F0",
            "aW9ucy5EZWZhdWx0QXBwcy5GcmllbmRzQXBwLk5ldHdvcmtpbmdNb2RlbHMu",
            "RnJpZW5kc0FwcFVzZXJNc2diBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::VrLifeShared.Core.Applications.DefaultApps.FriendsApp.NetworkingModels.FriendsAppUserMsgReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::VrLifeShared.Core.Applications.DefaultApps.FriendsApp.NetworkingModels.FriendsAppRequestsMsg), global::VrLifeShared.Core.Applications.DefaultApps.FriendsApp.NetworkingModels.FriendsAppRequestsMsg.Parser, new[]{ "ToUser", "FriendRequestsList" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class FriendsAppRequestsMsg : pb::IMessage<FriendsAppRequestsMsg> {
    private static readonly pb::MessageParser<FriendsAppRequestsMsg> _parser = new pb::MessageParser<FriendsAppRequestsMsg>(() => new FriendsAppRequestsMsg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FriendsAppRequestsMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VrLifeShared.Core.Applications.DefaultApps.FriendsApp.NetworkingModels.FriendsAppRequestsMsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FriendsAppRequestsMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FriendsAppRequestsMsg(FriendsAppRequestsMsg other) : this() {
      toUser_ = other.toUser_;
      friendRequestsList_ = other.friendRequestsList_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FriendsAppRequestsMsg Clone() {
      return new FriendsAppRequestsMsg(this);
    }

    /// <summary>Field number for the "toUser" field.</summary>
    public const int ToUserFieldNumber = 1;
    private ulong toUser_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong ToUser {
      get { return toUser_; }
      set {
        toUser_ = value;
      }
    }

    /// <summary>Field number for the "friendRequestsList" field.</summary>
    public const int FriendRequestsListFieldNumber = 2;
    private static readonly pb::FieldCodec<global::VrLifeShared.Core.Applications.DefaultApps.FriendsApp.NetworkingModels.FriendsAppUserMsg> _repeated_friendRequestsList_codec
        = pb::FieldCodec.ForMessage(18, global::VrLifeShared.Core.Applications.DefaultApps.FriendsApp.NetworkingModels.FriendsAppUserMsg.Parser);
    private readonly pbc::RepeatedField<global::VrLifeShared.Core.Applications.DefaultApps.FriendsApp.NetworkingModels.FriendsAppUserMsg> friendRequestsList_ = new pbc::RepeatedField<global::VrLifeShared.Core.Applications.DefaultApps.FriendsApp.NetworkingModels.FriendsAppUserMsg>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::VrLifeShared.Core.Applications.DefaultApps.FriendsApp.NetworkingModels.FriendsAppUserMsg> FriendRequestsList {
      get { return friendRequestsList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FriendsAppRequestsMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FriendsAppRequestsMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ToUser != other.ToUser) return false;
      if(!friendRequestsList_.Equals(other.friendRequestsList_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ToUser != 0UL) hash ^= ToUser.GetHashCode();
      hash ^= friendRequestsList_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ToUser != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ToUser);
      }
      friendRequestsList_.WriteTo(output, _repeated_friendRequestsList_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ToUser != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ToUser);
      }
      size += friendRequestsList_.CalculateSize(_repeated_friendRequestsList_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FriendsAppRequestsMsg other) {
      if (other == null) {
        return;
      }
      if (other.ToUser != 0UL) {
        ToUser = other.ToUser;
      }
      friendRequestsList_.Add(other.friendRequestsList_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ToUser = input.ReadUInt64();
            break;
          }
          case 18: {
            friendRequestsList_.AddEntriesFrom(input, _repeated_friendRequestsList_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
