// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatAppMsg.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels {

  /// <summary>Holder for reflection information generated from ChatAppMsg.proto</summary>
  public static partial class ChatAppMsgReflection {

    #region Descriptor
    /// <summary>File descriptor for ChatAppMsg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChatAppMsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBDaGF0QXBwTXNnLnByb3RvEkNWckxpZmVTaGFyZWQuQ29yZS5BcHBsaWNh",
            "dGlvbnMuRGVmYXVsdEFwcHMuQ2hhdEFwcC5OZXR3b3JraW5nTW9kZWxzGhFD",
            "aGF0UmVxdWVzdC5wcm90bxoTQ2hhdE9iamVjdE1zZy5wcm90bxoOQ2hhdExp",
            "c3QucHJvdG8irgIKCkNoYXRBcHBNc2cSYQoHcmVxdWVzdBgBIAEoCzJQLlZy",
            "TGlmZVNoYXJlZC5Db3JlLkFwcGxpY2F0aW9ucy5EZWZhdWx0QXBwcy5DaGF0",
            "QXBwLk5ldHdvcmtpbmdNb2RlbHMuQ2hhdFJlcXVlc3QSYAoEY2hhdBgCIAEo",
            "CzJSLlZyTGlmZVNoYXJlZC5Db3JlLkFwcGxpY2F0aW9ucy5EZWZhdWx0QXBw",
            "cy5DaGF0QXBwLk5ldHdvcmtpbmdNb2RlbHMuQ2hhdE9iamVjdE1zZxJbCgRs",
            "aXN0GAMgASgLMk0uVnJMaWZlU2hhcmVkLkNvcmUuQXBwbGljYXRpb25zLkRl",
            "ZmF1bHRBcHBzLkNoYXRBcHAuTmV0d29ya2luZ01vZGVscy5DaGF0TGlzdGIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatRequestReflection.Descriptor, global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatObjectMsgReflection.Descriptor, global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatListReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatAppMsg), global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatAppMsg.Parser, new[]{ "Request", "Chat", "List" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ChatAppMsg : pb::IMessage<ChatAppMsg> {
    private static readonly pb::MessageParser<ChatAppMsg> _parser = new pb::MessageParser<ChatAppMsg>(() => new ChatAppMsg());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ChatAppMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatAppMsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatAppMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatAppMsg(ChatAppMsg other) : this() {
      Request = other.request_ != null ? other.Request.Clone() : null;
      Chat = other.chat_ != null ? other.Chat.Clone() : null;
      List = other.list_ != null ? other.List.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatAppMsg Clone() {
      return new ChatAppMsg(this);
    }

    /// <summary>Field number for the "request" field.</summary>
    public const int RequestFieldNumber = 1;
    private global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatRequest request_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatRequest Request {
      get { return request_; }
      set {
        request_ = value;
      }
    }

    /// <summary>Field number for the "chat" field.</summary>
    public const int ChatFieldNumber = 2;
    private global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatObjectMsg chat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatObjectMsg Chat {
      get { return chat_; }
      set {
        chat_ = value;
      }
    }

    /// <summary>Field number for the "list" field.</summary>
    public const int ListFieldNumber = 3;
    private global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatList list_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatList List {
      get { return list_; }
      set {
        list_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ChatAppMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ChatAppMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Request, other.Request)) return false;
      if (!object.Equals(Chat, other.Chat)) return false;
      if (!object.Equals(List, other.List)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (request_ != null) hash ^= Request.GetHashCode();
      if (chat_ != null) hash ^= Chat.GetHashCode();
      if (list_ != null) hash ^= List.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (request_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Request);
      }
      if (chat_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Chat);
      }
      if (list_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(List);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (request_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Request);
      }
      if (chat_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Chat);
      }
      if (list_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(List);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ChatAppMsg other) {
      if (other == null) {
        return;
      }
      if (other.request_ != null) {
        if (request_ == null) {
          request_ = new global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatRequest();
        }
        Request.MergeFrom(other.Request);
      }
      if (other.chat_ != null) {
        if (chat_ == null) {
          chat_ = new global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatObjectMsg();
        }
        Chat.MergeFrom(other.Chat);
      }
      if (other.list_ != null) {
        if (list_ == null) {
          list_ = new global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatList();
        }
        List.MergeFrom(other.List);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (request_ == null) {
              request_ = new global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatRequest();
            }
            input.ReadMessage(request_);
            break;
          }
          case 18: {
            if (chat_ == null) {
              chat_ = new global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatObjectMsg();
            }
            input.ReadMessage(chat_);
            break;
          }
          case 26: {
            if (list_ == null) {
              list_ = new global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatList();
            }
            input.ReadMessage(list_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
