// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatList.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels {

  /// <summary>Holder for reflection information generated from ChatList.proto</summary>
  public static partial class ChatListReflection {

    #region Descriptor
    /// <summary>File descriptor for ChatList.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChatListReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5DaGF0TGlzdC5wcm90bxJDVnJMaWZlU2hhcmVkLkNvcmUuQXBwbGljYXRp",
            "b25zLkRlZmF1bHRBcHBzLkNoYXRBcHAuTmV0d29ya2luZ01vZGVscxoTQ2hh",
            "dE9iamVjdE1zZy5wcm90byJsCghDaGF0TGlzdBJgCgRsaXN0GAEgAygLMlIu",
            "VnJMaWZlU2hhcmVkLkNvcmUuQXBwbGljYXRpb25zLkRlZmF1bHRBcHBzLkNo",
            "YXRBcHAuTmV0d29ya2luZ01vZGVscy5DaGF0T2JqZWN0TXNnYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatObjectMsgReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatList), global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatList.Parser, new[]{ "List" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ChatList : pb::IMessage<ChatList> {
    private static readonly pb::MessageParser<ChatList> _parser = new pb::MessageParser<ChatList>(() => new ChatList());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ChatList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatListReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatList(ChatList other) : this() {
      list_ = other.list_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatList Clone() {
      return new ChatList(this);
    }

    /// <summary>Field number for the "list" field.</summary>
    public const int ListFieldNumber = 1;
    private static readonly pb::FieldCodec<global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatObjectMsg> _repeated_list_codec
        = pb::FieldCodec.ForMessage(10, global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatObjectMsg.Parser);
    private readonly pbc::RepeatedField<global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatObjectMsg> list_ = new pbc::RepeatedField<global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatObjectMsg>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::VrLifeShared.Core.Applications.DefaultApps.ChatApp.NetworkingModels.ChatObjectMsg> List {
      get { return list_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ChatList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ChatList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!list_.Equals(other.list_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= list_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      list_.WriteTo(output, _repeated_list_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += list_.CalculateSize(_repeated_list_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ChatList other) {
      if (other == null) {
        return;
      }
      list_.Add(other.list_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            list_.AddEntriesFrom(input, _repeated_list_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
